server:
  port: 8080
spring:
  application:
    name: agouti1
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: ${server.port}
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 1
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://abc-eureka-server.dev.cnabc-inc.com/eureka/



